### ISSUE TITLE
Is there anyway to disable kube-proxy during the install?

### ISSUE THREAD

**Issue by liyihuang** [karmab/aicli#56]
I'm using this tool to automate my OCP install on KVM with cilium. it works great but it looks like I can't disable the kube proxy during the install. Is it true? Is this limited by aicli or  assisted installer? 

I will use this feature https://cilium.io/use-cases/kube-proxy/ so kube-proxy is optional to me

```
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  creationTimestamp: null
  name: cluster
spec:
  deployKubeProxy: false
  clusterNetwork:
  - cidr: 10.253.0.0/16
    hostPrefix: 24
  externalIP:
    policy: {}
  networkType: Cilium
  serviceNetwork:
  - 172.31.0.0/16
 ```
